#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Multiple monitor support
# sh $HOME/.config/bspwm/dual_monitors.sh
#

MONITOR_1="DP-0"
MONITOR_2="HDMI-0"

# Может пригодитсься
# xrandr \
#     --output "$INTERNAL_MONITOR" \
#     --mode 1920x1080 \
#     --rate 165 \
#     --pos 0x0 \
#     --rotate normal
#
# xrandr \
#     --output "$EXTERNAL_MONITOR" \
#     --primary \
#     --mode 3840x2160 \
#     --rate 160 \
#     --pos 1920x0 \
#     --rotate normal

bspc monitor "$MONITOR_1" -d 1 3 5 7
bspc monitor "$MONITOR_2" -d 2 4 6 8

bspc wm -O "$MONITOR_1" "$MONITOR_2"

# Window borders (Auto-Generate)
bspc config focus_follows_pointer true
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating

# start resources
xrdb merge ~/.Xresources

# Random Wallpaper Script
sh $HOME/bin/random_wallpaper

# Run polybar
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# == autostart ==
pkill flameshot; flameshot &

# run cursor tracker - на любителя темка 
# pkill cursor_tracker ; ~/bin/cursor_tracker.sh
